#449 Cell Size Analysis page with download to executable
Data-Boom/SOEN490 pull request #480
Opened 2021-03-09 22:05 UTC by JeremiahTee

Include instructions and download button to executable
Current executable is a placeholder (python installer) -> will put correct executable once it is done from #444 
This PR also addressed the small feedback from Prof to change everything from "Data Cell Analysis" to "Cell Size Analysis" #289

2021-03-11 22:33 UTC, ds161833 approved these changes

2021-03-12 01:38 UTC, TiraFire requested changes
Would definitely add more information about how to use the app, think you could add some examples, pictures, etc now that the tool is finished?

2021-03-14 22:29 UTC, JeremiahTee commented
> Would definitely add more information about how to use the app, think you could add some examples, pictures, etc now that the tool is finished?

Added more instructions on how to use buttons & demo gif

2021-03-15 03:57 UTC, TiraFire approved these changes

2021-03-16 02:47 UTC, merged