User Saved Dataset Page
Data-Boom/SOEN490 pull request #481
Opened 2021-03-09 22:47 UTC by lposo

Users can now view and click the datasets they have favorited.

![image](https://user-images.githubusercontent.com/46732530/110549033-7d2c4080-80ff-11eb-9a5e-ab6aaee8e5e5.png)

2021-03-09 22:59 UTC, laithAwad requested changes
The table looks a bit off, why does it have too much space on the right side and not enough on the left? can you centre it please, and check the sonar code smells as well.
good work overall!

2021-03-10 03:09 UTC, ds161833 reviewed
perfect 👍

2021-03-10 11:10 UTC, laithAwad approved these changes

2021-03-11 03:41 UTC, Vatika1 approved these changes
now it looks good :)

2021-03-11 03:46 UTC, merged