Graph Colours and Shapes #164
Data-Boom/SOEN490 pull request #534
Opened 2021-04-01 23:32 UTC by lposo

Now, users can specify the colour and shape for a given dataset on the graph. There are four choices for shape. Colours can be changed by using the colour picker.

![image](https://user-images.githubusercontent.com/46732530/113364224-f4c94600-9320-11eb-9a9f-3739209beda7.png)

2021-04-02 12:02 UTC, ds161833 requested changes
![image](https://user-images.githubusercontent.com/22376976/113413875-a4d29980-9389-11eb-8bc7-40ce04e3a32c.png)
can you have it say "circle" by default
also instad of displayed a text, can you just display a little colored squeare maybe
![image](https://user-images.githubusercontent.com/22376976/113413923-bf0c7780-9389-11eb-8cf6-723fbf44cdec.png)
so that people can identify their datasetsby the color, by text it's pretty hard

2021-04-02 12:07 UTC, ds161833 requested changes
![image](https://user-images.githubusercontent.com/22376976/113414153-51148000-938a-11eb-981d-026c80261c49.png)
can you also have the two buttons be rightmost on the dataset row? so just swap color/shape picker, with the eye and bin buttons

2021-04-02 13:57 UTC, ds161833 approved these changes

2021-04-02 13:58 UTC, ds161833 approved these changes
nice! why did you remove package-lock.json though
![image](https://user-images.githubusercontent.com/22376976/113421950-ebc88b00-9399-11eb-982f-251d90da026a.png)

2021-04-02 13:59 UTC, ds161833 commented on Client/src/Models/Datasets/IDatasetRowModel.tsx
> +  color: "circle",
wait, color circle?

2021-04-02 13:59 UTC, ds161833 commented on Client/src/Models/Datasets/IDatasetRowModel.tsx
> +  color: "circle",
you meant to have "shape" circle?

2021-04-02 13:59 UTC, ds161833 commented on Client/src/Models/Datasets/IDatasetRowModel.tsx
> +  color: "circle",
add a default color too actually

2021-04-02 14:07 UTC, ds161833 requested changes
![image](https://user-images.githubusercontent.com/22376976/113422697-27178980-939b-11eb-89ba-1847988bb76e.png)
override the default bullet.stroke too

2021-04-02 16:06 UTC, lposo commented on Client/src/Models/Datasets/IDatasetRowModel.tsx
> +  color: "circle",
Fixed in latest push

2021-04-02 16:33 UTC, ds161833 approved these changes

2021-04-03 06:44 UTC, laithAwad approved these changes

2021-04-03 13:23 UTC, merged