Added an admin page that handles all admin functions
Data-Boom/SOEN490 pull request #536
Opened 2021-04-03 10:22 UTC by laithAwad

Added admin page and removed those tabs from the profile page, also added a check for a super admin to view certain tabs

2021-04-03 15:38 UTC, Mehrdadmaskull approved these changes
Code looks nice and clean, LGTM

2021-04-03 19:04 UTC, Vatika1 commented on Client/src/Components/Admin/AdminPageView.tsx
> +}
nice

2021-04-03 19:05 UTC, Vatika1 commented on Client/src/Components/Admin/AdminPageView.tsx
> +                    </Tabs>
nice

2021-04-03 19:06 UTC, Vatika1 approved these changes
looks good to me. good work

2021-04-04 04:11 UTC, ds161833 requested changes

2021-04-04 04:11 UTC, ds161833 commented on Client/src/Common/Consts/Routes.tsx
> +  adminPageRoute: { route: '/adminPage', permission: 1 }
can you change the permissions to 2

2021-04-04 04:34 UTC, laithAwad commented on Client/src/Common/Consts/Routes.tsx
> +  adminPageRoute: { route: '/adminPage', permission: 1 }
done

2021-04-04 11:12 UTC, ds161833 approved these changes

2021-04-04 11:30 UTC, merged